# -*- coding: utf-8 -*-
"""codigo_sc_recuperacao

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TtdGhKcNlR4fn_jQGiF5gsPhIT33I5XT
"""

#!/usr/bin/env python3
"""
CONTADOR SANTA CRUZ v4.3 + AUTO-RECUPERAÇÃO
Sistema que resolve automaticamente problemas após 3+ horas
"""

import gspread
from google.oauth2.service_account import Credentials
from datetime import datetime, timedelta
import logging
import os
import traceback
import time
import json
import serial
import threading
import serial.tools.list_ports
import gc
from dotenv import load_dotenv

# Configuração básica de logging com rotação
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('santa_cruz_auto_recovery.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger('santa_cruz_auto_recovery')

# Configurando o nível de log para outros módulos
logging.getLogger('urllib3').setLevel(logging.WARNING)
logging.getLogger('gspread').setLevel(logging.WARNING)

load_dotenv()

# Configuração do radar
RADAR_CONFIG = {
    'id': 'RADAR_1',
    'name': 'Contador de Pessoas',
    'port': '/dev/ttyACM0',
    'baudrate': 115200,
    'spreadsheet_id': '1zVVyL6D9XSrzFvtDxaGJ-3CdniD-gG3Q-bUUXyqr3D4',
    'color': '🔴',
    'description': 'Contador v4.3: Arduino minimal + Auto-Recovery'
}

class AutoRecoveryGoogleSheetsManager:
    """GoogleSheetsManager com auto-recuperação integrada"""

    def __init__(self, creds_path, spreadsheet_id, radar_id):
        SCOPES = [
            'https://www.googleapis.com/auth/spreadsheets',
            'https://www.googleapis.com/auth/drive',
            'https://www.googleapis.com/auth/drive.file'
        ]
        self.radar_id = radar_id
        self.spreadsheet_id = spreadsheet_id
        self.creds_path = creds_path

        # Controle de auto-recuperação
        self.last_successful_write = datetime.now()
        self.consecutive_failures = 0
        self.max_failures_before_recovery = 3
        self.recovery_attempts = 0
        self.max_recovery_attempts = 5

        # Conecta inicialmente
        self._connect_with_recovery()
        self._setup_headers()

    def _connect_with_recovery(self):
        """Conecta com sistema de recuperação robusto"""
        for attempt in range(3):
            try:
                # Re-cria credenciais sempre (evita token expirado)
                SCOPES = [
                    'https://www.googleapis.com/auth/spreadsheets',
                    'https://www.googleapis.com/auth/drive',
                    'https://www.googleapis.com/auth/drive.file'
                ]
                self.creds = Credentials.from_service_account_file(self.creds_path, scopes=SCOPES)
                self.gc = gspread.authorize(self.creds)

                self.spreadsheet = self.gc.open_by_key(self.spreadsheet_id)
                self.worksheet = self.spreadsheet.get_worksheet(0)

                # Testa leitura (operação leve)
                headers = self.worksheet.row_values(1)

                logger.info(f"✅ Google Sheets conectado (tentativa {attempt + 1})")
                self.consecutive_failures = 0
                return True

            except Exception as e:
                logger.warning(f"⚠️ Falha na conexão tentativa {attempt + 1}: {e}")
                if attempt < 2:
                    time.sleep((attempt + 1) * 5)  # Backoff

        raise Exception("Falha ao conectar após múltiplas tentativas")

    def _setup_headers(self):
        """Configura cabeçalhos (com retry)"""
        try:
            headers = self.worksheet.row_values(1)
            expected_headers = [
                'radar_id', 'timestamp', 'person_count', 'person_id',
                'zone', 'distance', 'confidence', 'total_detected', 'max_simultaneous'
            ]

            if not headers or len(headers) < 9:
                logger.info("🔧 Configurando cabeçalhos...")
                self.worksheet.clear()
                self.worksheet.append_row(expected_headers)
        except Exception as e:
            logger.warning(f"⚠️ Erro configurando cabeçalhos: {e}")

    def append_row_with_auto_recovery(self, row):
        """Envia linha com auto-recuperação completa"""
        for attempt in range(3):
            try:
                self.worksheet.append_row(row)
                self.last_successful_write = datetime.now()
                self.consecutive_failures = 0
                return True

            except Exception as e:
                self.consecutive_failures += 1
                error_str = str(e).lower()

                logger.warning(f"⚠️ Erro envio (tentativa {attempt + 1}): {e}")

                # Tipos específicos de erro
                if "quota" in error_str or "429" in error_str:
                    wait_time = (attempt + 1) * 60  # 1min, 2min, 3min
                    logger.warning(f"⚠️ Quota exceeded - aguardando {wait_time}s")
                    time.sleep(wait_time)

                elif "401" in error_str or "unauthorized" in error_str:
                    logger.warning("🔑 Token expirado - reconectando...")
                    try:
                        self._connect_with_recovery()
                        time.sleep(2)
                    except:
                        pass

                elif "network" in error_str or "connection" in error_str:
                    logger.warning("🌐 Problema de rede - aguardando...")
                    time.sleep(10 * (attempt + 1))

                else:
                    # Erro genérico - tenta reconectar
                    try:
                        self._connect_with_recovery()
                        time.sleep(5)
                    except:
                        time.sleep(10)

        # Se chegou aqui, todas as tentativas falharam
        logger.error(f"❌ Falha total no envio após 3 tentativas")

        # Auto-recuperação extrema
        if self.consecutive_failures >= self.max_failures_before_recovery:
            return self._attempt_full_recovery()

        return False

    def _attempt_full_recovery(self):
        """Recuperação completa do sistema Google Sheets"""
        if self.recovery_attempts >= self.max_recovery_attempts:
            logger.error("🚨 Máximo de recuperações atingido!")
            return False

        self.recovery_attempts += 1
        logger.info(f"🔄 Recuperação completa #{self.recovery_attempts}")

        try:
            # 1. Força garbage collection
            gc.collect()

            # 2. Aguarda mais tempo
            time.sleep(30)

            # 3. Reconecta completamente
            self._connect_with_recovery()

            # 4. Testa com dados simples
            test_row = [
                self.radar_id,
                datetime.now().strftime('%d/%m/%Y %H:%M:%S'),
                0, "Recovery_Test", "RECOVERY", "0", "100", 0, 0
            ]

            self.worksheet.append_row(test_row)

            logger.info("✅ Recuperação completa bem-sucedida!")
            self.consecutive_failures = 0
            return True

        except Exception as e:
            logger.error(f"❌ Falha na recuperação completa: {e}")
            return False

    def health_check(self):
        """Verifica saúde da conexão"""
        time_since_success = datetime.now() - self.last_successful_write

        if time_since_success > timedelta(minutes=15):
            logger.warning(f"⚠️ Sem envios há {time_since_success}")
            return False

        if self.consecutive_failures > 5:
            logger.warning(f"⚠️ {self.consecutive_failures} falhas consecutivas")
            return False

        return True

class ZoneManager:
    """Sistema de zonas do Santa Cruz"""
    def __init__(self):
        self.ZONA_CONFIGS = {
            # LADO ESQUERDO (X < -0.3)
            'SALA_REBOCO': {
                'x_min': -3.5, 'x_max': -0.3,
                'y_min': 0.3, 'y_max': 3.8,
                'distance_range': (1.0, 4.0)
            },
            'IGREJINHA': {
                'x_min': -3.0, 'x_max': -0.2,
                'y_min': 2.8, 'y_max': 6.0,
                'distance_range': (2.5, 6.0)
            },
            # CENTRO (X entre -0.8 e 0.8)
            'CENTRO': {
                'x_min': -1.0, 'x_max': 1.0,
                'y_min': 1.0, 'y_max': 4.5,
                'distance_range': (2.0, 5.0)
            },
            # LADO DIREITO (X > 0.5)
            'ARGOLA': {
                'x_min': 0.3, 'x_max': 3.0,
                'y_min': 4.0, 'y_max': 7.5,
                'distance_range': (4.0, 8.0)
            },
            'BEIJO': {
                'x_min': 0.5, 'x_max': 3.5,
                'y_min': 2.0, 'y_max': 5.5,
                'distance_range': (3.5, 7.5)
            },
            'PESCARIA': {
                'x_min': 0.8, 'x_max': 4.0,
                'y_min': 0.2, 'y_max': 4.0,
                'distance_range': (4.0, 9.0)
            }
        }

    def get_zone(self, x, y):
        """Determinar zona baseada nas ativações específicas"""
        distance = self.get_distance(x, y)

        for zona_name, config in self.ZONA_CONFIGS.items():
            if (config['x_min'] <= x <= config['x_max'] and
                config['y_min'] <= y <= config['y_max'] and
                config['distance_range'][0] <= distance <= config['distance_range'][1]):
                return zona_name

        return 'FORA_ATIVACOES'

    def get_distance(self, x, y):
        """Calcular distância do radar"""
        import math
        return math.sqrt(x**2 + y**2)

    def get_zone_description(self, zone_name):
        """Retorna descrição amigável da zona"""
        descriptions = {
            'SALA_REBOCO': 'Sala de Reboco',
            'IGREJINHA': 'Igrejinha',
            'CENTRO': 'Centro',
            'ARGOLA': 'Jogo da Argola',
            'BEIJO': 'Barraca do Beijo',
            'PESCARIA': 'Pescaria',
            'FORA_ATIVACOES': 'Fora das Ativações'
        }
        return descriptions.get(zone_name, zone_name)

class AutoRecoveryRadarCounter:
    """Contador COMPLETO com sistema de auto-recuperação integrado"""

    def __init__(self, config):
        self.config = config
        self.radar_id = config['id']
        self.radar_name = config['name']
        self.port = config['port']
        self.baudrate = config['baudrate']
        self.color = config['color']
        self.description = config['description']

        # Sistema de auto-recuperação
        self.start_time = datetime.now()
        self.last_data_received = datetime.now()
        self.last_sheets_success = datetime.now()
        self.system_restart_count = 0
        self.max_system_restarts = 3

        # Estado do radar
        self.serial_connection = None
        self.is_running = False
        self.receive_thread = None
        self.gsheets_manager = None
        self.zone_manager = ZoneManager()  # ✅ ADICIONADO

        # ✅ SISTEMA COMPLETO DE CONTAGEM (igual ao original)
        self.current_people = {}
        self.previous_people = {}
        self.people_history = {}
        self.total_people_detected = 0
        self.max_simultaneous_people = 0
        self.session_start_time = datetime.now()

        # Configurações de tracking
        self.exit_timeout = 3.0
        self.reentry_timeout = 10.0
        self.last_update_time = time.time()

        # Configurações anti-quota
        self.last_sheets_write = 0
        self.sheets_write_interval = 30.0
        self.pending_data = []

        # ✅ ESTATÍSTICAS DETALHADAS (igual ao original)
        self.entries_count = 0
        self.exits_count = 0
        self.unique_people_today = set()

        # Thread de monitoramento
        self.monitoring_thread = None

    def start_health_monitoring(self):
        """Inicia monitoramento de saúde em background"""
        self.monitoring_thread = threading.Thread(target=self._health_monitoring_loop, daemon=True)
        self.monitoring_thread.start()
        logger.info("🔄 Monitoramento de saúde iniciado")

    def _health_monitoring_loop(self):
        """Loop de monitoramento de saúde"""
        while self.is_running:
            try:
                time.sleep(60)  # Verifica a cada minuto
                self._check_system_health()
            except Exception as e:
                logger.error(f"❌ Erro no monitoramento: {e}")
                time.sleep(30)

    def _check_system_health(self):
        """Verifica saúde geral do sistema"""
        now = datetime.now()

        # 1. Verifica recebimento de dados serial
        time_since_data = now - self.last_data_received
        if time_since_data > timedelta(minutes=5):
            logger.warning(f"⚠️ Sem dados seriais há {time_since_data}")
            self._attempt_serial_recovery()

        # 2. Verifica envios para planilha
        time_since_sheets = now - self.last_sheets_success
        if time_since_sheets > timedelta(minutes=10):
            logger.warning(f"⚠️ Sem envios há {time_since_sheets}")
            if self.gsheets_manager:
                self.gsheets_manager._attempt_full_recovery()

        # 3. Verifica uso de memória
        try:
            import psutil
            process = psutil.Process()
            memory_mb = process.memory_info().rss / 1024 / 1024

            if memory_mb > 200:  # 200MB limite
                logger.warning(f"⚠️ Memória alta: {memory_mb:.1f}MB")
                self._cleanup_memory()

        except ImportError:
            pass  # psutil não disponível
        except Exception as e:
            logger.debug(f"Erro verificando memória: {e}")

        # 4. Restart preventivo após 6 horas
        runtime = now - self.start_time
        if runtime > timedelta(hours=6):
            logger.info(f"⏰ Runtime {runtime} - restart preventivo recomendado")
            self._attempt_system_restart()

    def _cleanup_memory(self):
        """Limpa memória e buffers"""
        try:
            # Limpa buffer de dados pendentes
            if len(self.pending_data) > 20:
                self.pending_data = self.pending_data[-10:]
                logger.info("🧹 Buffer limpo")

            # Força garbage collection
            gc.collect()

        except Exception as e:
            logger.error(f"❌ Erro limpando memória: {e}")

    def _attempt_serial_recovery(self):
        """Tenta recuperar conexão serial"""
        try:
            logger.info("🔄 Tentando recuperar conexão serial...")

            # Fecha conexão atual
            if self.serial_connection:
                try:
                    self.serial_connection.close()
                except:
                    pass
                time.sleep(2)

            # Tenta reconectar
            if self.connect():
                logger.info("✅ Conexão serial recuperada!")
                return True
            else:
                logger.error("❌ Falha na recuperação serial")
                return False

        except Exception as e:
            logger.error(f"❌ Erro na recuperação serial: {e}")
            return False

    def _attempt_system_restart(self):
        """Restart preventivo do sistema"""
        if self.system_restart_count >= self.max_system_restarts:
            logger.error("🚨 Máximo de restarts atingido")
            return False

        self.system_restart_count += 1
        logger.info(f"🔄 Restart preventivo #{self.system_restart_count}")

        try:
            # Para sistema
            self.stop()
            time.sleep(5)

            # Re-inicializa
            self.start(self.gsheets_manager)

            # Reset contadores
            self.start_time = datetime.now()

            logger.info("✅ Restart preventivo concluído")
            return True

        except Exception as e:
            logger.error(f"❌ Falha no restart preventivo: {e}")
            return False

    def connect(self):
        """Conecta à porta serial (versão original)"""
        max_attempts = 3

        for attempt in range(max_attempts):
            try:
                if not os.path.exists(self.port):
                    logger.warning(f"Porta {self.port} não existe, detectando...")
                    detected_port = self.find_serial_port()
                    if detected_port:
                        self.port = detected_port
                    else:
                        logger.error(f"Tentativa {attempt + 1}: Nenhuma porta encontrada")
                        time.sleep(2)
                        continue

                if hasattr(self, 'serial_connection') and self.serial_connection:
                    try:
                        self.serial_connection.close()
                    except:
                        pass

                logger.info(f"Tentativa {attempt + 1}: Conectando à porta {self.port}")

                self.serial_connection = serial.Serial(
                    port=self.port,
                    baudrate=self.baudrate,
                    timeout=2,
                    write_timeout=2,
                    bytesize=serial.EIGHTBITS,
                    parity=serial.PARITY_NONE,
                    stopbits=serial.STOPBITS_ONE
                )

                time.sleep(3)

                if self.serial_connection.is_open:
                    logger.info(f"✅ Conexão estabelecida com sucesso!")
                    return True

            except serial.SerialException as e:
                logger.error(f"❌ Erro serial na tentativa {attempt + 1}: {str(e)}")
            except Exception as e:
                logger.error(f"❌ Erro geral na tentativa {attempt + 1}: {str(e)}")

            if attempt < max_attempts - 1:
                wait_time = (attempt + 1) * 2
                logger.info(f"⏳ Aguardando {wait_time}s...")
                time.sleep(wait_time)

        logger.error(f"❌ Falha ao conectar após {max_attempts} tentativas")
        return False

    def find_serial_port(self):
        """Detecta porta serial automaticamente"""
        ports = list(serial.tools.list_ports.comports())
        if not ports:
            return None

        # Primeiro tenta a porta configurada
        for port in ports:
            if port.device == self.port:
                return self.port

        # Se não encontrou, procura por dispositivos apropriados
        for port in ports:
            desc_lower = port.description.lower()
            if any(term in desc_lower for term in
                  ['usb', 'serial', 'uart', 'cp210', 'ch340', 'ft232', 'arduino', 'esp32']):
                logger.warning(f"Porta {self.port} não encontrada, tentando usar {port.device}")
                return port.device

        return None

    def start(self, gsheets_manager):
        """Inicia o radar com auto-recuperação"""
        self.gsheets_manager = gsheets_manager

        if not self.connect():
            return False

        self.is_running = True
        self.receive_thread = threading.Thread(target=self.receive_data_loop, daemon=True)
        self.receive_thread.start()

        # Inicia monitoramento de saúde
        self.start_health_monitoring()

        logger.info(f"🚀 Radar com auto-recuperação iniciado!")
        return True

    def stop(self):
        """Para o radar"""
        self.is_running = False

        if self.serial_connection:
            try:
                self.serial_connection.close()
            except:
                pass

        if self.receive_thread and self.receive_thread.is_alive():
            self.receive_thread.join(timeout=2)

        logger.info("🛑 Radar parado!")

    def receive_data_loop(self):
        """Loop de dados com auto-recuperação"""
        buffer = ""
        consecutive_errors = 0
        max_consecutive_errors = 5

        while self.is_running:
            try:
                if not self.serial_connection or not self.serial_connection.is_open:
                    logger.warning("⚠️ Conexão perdida, tentando reconectar...")
                    if self.connect():
                        consecutive_errors = 0
                        buffer = ""
                        continue
                    else:
                        consecutive_errors += 1
                        time.sleep(5)
                        continue

                in_waiting = self.serial_connection.in_waiting or 0
                data = self.serial_connection.read(in_waiting or 1)

                if data:
                    consecutive_errors = 0
                    self.last_data_received = datetime.now()  # Marca recebimento

                    text = data.decode('utf-8', errors='ignore')
                    buffer += text

                    if '\n' in buffer:
                        lines = buffer.split('\n')
                        buffer = lines[-1]

                        for line in lines[:-1]:
                            line = line.strip()
                            if not line or not line.startswith('{'):
                                continue

                            try:
                                data_json = json.loads(line)
                                self.process_json_data(data_json)
                            except json.JSONDecodeError:
                                logger.debug(f"JSON inválido: {line[:50]}...")
                            except Exception as e:
                                logger.error(f"Erro processando JSON: {e}")

                time.sleep(0.01)

            except Exception as e:
                consecutive_errors += 1
                logger.error(f"❌ Erro no loop: {str(e)}")
                time.sleep(2)

                if consecutive_errors >= max_consecutive_errors:
                    logger.warning("⚠️ Muitos erros - pausando...")
                    time.sleep(10)
                    consecutive_errors = 0

    def convert_timestamp(self, timestamp_ms):
        """Converte timestamp para formato brasileiro"""
        try:
            dt = datetime.now()
            return dt.strftime('%d/%m/%Y %H:%M:%S')
        except Exception as e:
            logger.debug(f"Erro na conversão de timestamp: {e}")
            return datetime.now().strftime('%d/%m/%Y %H:%M:%S')

    def format_duration(self, duration_ms):
        """Formata duração em milissegundos para formato legível"""
        try:
            if duration_ms < 1000:
                return f"{int(duration_ms)}ms"
            elif duration_ms < 60000:
                seconds = duration_ms / 1000
                return f"{seconds:.1f}s"
            elif duration_ms < 3600000:
                minutes = duration_ms / 60000
                return f"{minutes:.1f}min"
            else:
                hours = duration_ms / 3600000
                return f"{hours:.1f}h"
        except:
            return "N/A"

    def update_people_count(self, person_count, active_people):
        """Sistema COMPLETO de tracking (igual ao original + auto-recovery)"""
        current_time = time.time()

        # Cria IDs únicos baseados em posição estável
        current_people_dict = {}

        for i, person in enumerate(active_people):
            x_pos = person.get('x_pos', 0)
            y_pos = person.get('y_pos', 0)
            distance = person.get('distance_raw', 0)

            # ✅ CALCULA ZONA ESPECÍFICA usando coordenadas x,y
            zone = self.zone_manager.get_zone(x_pos, y_pos)
            person["zone"] = zone

            # ID baseado na posição arredondada (estável)
            stable_id = f"P_{zone}_{distance:.1f}_{i}"

            # Procura se já existe pessoa similar
            found_existing = None
            for existing_id, existing_person in self.current_people.items():
                existing_dist = existing_person.get('distance_raw', 0)
                existing_zone = existing_person.get('zone', '')

                if (existing_zone == zone and
                    abs(existing_dist - distance) < 0.3):
                    found_existing = existing_id
                    break

            if found_existing:
                current_people_dict[found_existing] = person
                current_people_dict[found_existing]['last_seen'] = current_time
            else:
                # Nova pessoa detectada
                person['first_seen'] = current_time
                person['last_seen'] = current_time
                person['distance_smoothed'] = distance
                person['confidence'] = 85
                person['stationary'] = False
                current_people_dict[stable_id] = person

        # Detecta ENTRADAS REAIS
        new_entries = []
        for person_id, person_info in current_people_dict.items():
            if person_id not in self.current_people:
                is_really_new = True
                for old_id, old_person in self.previous_people.items():
                    old_zone = old_person.get('zone', '')
                    old_dist = old_person.get('distance_raw', 0)
                    new_zone = person_info.get('zone', '')
                    new_dist = person_info.get('distance_raw', 0)

                    if (old_zone == new_zone and
                        abs(old_dist - new_dist) < 0.5 and
                        (current_time - old_person.get('last_seen', 0)) < 2.0):
                        is_really_new = False
                        break

                if is_really_new:
                    new_entries.append(person_id)
                    self.total_people_detected += 1
                    self.entries_count += 1
                    self.unique_people_today.add(person_id)
                    zone = person_info.get('zone', 'DESCONHECIDA')
                    dist = person_info.get('distance_raw', 0)
                    logger.info(f"🆕 ENTRADA REAL: {zone} {dist:.1f}m (Total: {self.total_people_detected})")

        # Detecta SAÍDAS REAIS
        exits = []
        for person_id, person_info in self.current_people.items():
            if person_id not in current_people_dict:
                last_seen = person_info.get('last_seen', 0)
                if (current_time - last_seen) > 1.0:
                    exits.append(person_id)
                    self.exits_count += 1
                    zone = person_info.get('zone', 'DESCONHECIDA')
                    dist = person_info.get('distance_raw', 0)
                    logger.info(f"🚪 SAÍDA REAL: {zone} {dist:.1f}m (Entradas: {self.entries_count}, Saídas: {self.exits_count})")

        # Atualiza estado
        self.previous_people = self.current_people.copy()
        self.current_people = current_people_dict

        # Atualiza máximo simultâneo
        current_simultaneous = len(current_people_dict)
        if current_simultaneous > self.max_simultaneous_people:
            self.max_simultaneous_people = current_simultaneous
            logger.info(f"📊 NOVO MÁXIMO SIMULTÂNEO: {self.max_simultaneous_people} pessoas")

        # Log apenas se houve mudanças reais
        if new_entries or exits:
            logger.info(f"📊 STATUS: {current_simultaneous} ativas | {self.total_people_detected} total | Máx: {self.max_simultaneous_people}")

        self.last_update_time = current_time

    def process_json_data(self, data_json):
        """Processa dados JSON COMPLETO (igual ao original + auto-recovery)"""
        try:
            radar_id = data_json.get("radar_id", self.radar_id)
            timestamp_ms = data_json.get("timestamp_ms", 0)
            person_count = data_json.get("person_count", 0)
            active_people = data_json.get("active_people", [])
            tracking_method = data_json.get("tracking_method", "hybrid_multi")
            session_duration_ms = data_json.get("session_duration_ms", 0)
            update_rate_hz = data_json.get("update_rate_hz", 8.3)

            # Converte timestamp para formato legível
            formatted_timestamp = self.convert_timestamp(timestamp_ms)

            # Atualiza contadores locais com lógica COMPLETA
            self.update_people_count(person_count, active_people)

            # ✅ DISPLAY COMPLETO (igual ao original)
            os.system('clear')
            print(f"\n{self.color} ═══ CONTADOR ROBUSTO + AUTO-RECOVERY ═══")
            print(f"⏰ {formatted_timestamp}")
            print(f"📡 {radar_id} | 👥 ATIVAS: {person_count}")
            print(f"🎯 TOTAL DETECTADAS: {self.total_people_detected} | 📊 MÁXIMO SIMULTÂNEO: {self.max_simultaneous_people}")
            print(f"🔄 ENTRADAS: {self.entries_count} | 🚪 SAÍDAS: {self.exits_count}")
            print(f"🆔 PESSOAS ÚNICAS: {len(self.unique_people_today)}")

            # ✅ STATUS AUTO-RECOVERY
            runtime = datetime.now() - self.start_time
            time_since_sheets = datetime.now() - self.last_sheets_success
            duration_str = self.format_duration(runtime.total_seconds() * 1000)
            print(f"⏱️ SESSÃO: {duration_str} | 🔄 Restarts: {self.system_restart_count}")

            # Status do envio para planilha
            pending_count = len(self.pending_data)
            time_since_last_send = time.time() - self.last_sheets_write
            next_send_in = max(0, self.sheets_write_interval - time_since_last_send)
            if pending_count > 0:
                print(f"📋 BUFFER: {pending_count} linhas | ⏳ Próximo envio em: {next_send_in:.0f}s")
            else:
                print(f"📋 PLANILHA: Sincronizada ✅ | Último envio: {time_since_sheets}")

            if active_people and len(active_people) > 0:
                print(f"\n👥 PESSOAS DETECTADAS AGORA ({len(active_people)}):")
                print(f"{'Ativação':<15} {'Dist(m)':<7} {'X,Y':<10} {'Conf%':<5} {'Status':<8} {'Desde':<8}")
                print("-" * 65)

                current_time = time.time()
                for i, person in enumerate(active_people):
                    confidence = person.get("confidence", 85)
                    distance_raw = person.get("distance_raw", 0)
                    distance_smoothed = person.get("distance_smoothed", distance_raw)
                    x_pos = person.get("x_pos", 0)
                    y_pos = person.get("y_pos", 0)
                    stationary = person.get("stationary", False)

                    # ✅ CALCULA ZONA usando coordenadas x,y
                    zone = self.zone_manager.get_zone(x_pos, y_pos)
                    person["zone"] = zone

                    # Encontra ID da nossa lógica interna
                    our_person_id = None
                    for internal_id, internal_person in self.current_people.items():
                        internal_dist = internal_person.get('distance_raw', internal_person.get('distance_smoothed', 0))
                        if (abs(internal_dist - distance_raw) < 0.1 and
                            internal_person.get('zone', '') == zone):
                            our_person_id = internal_id
                            break

                    # Calcula tempo desde primeira detecção
                    if our_person_id and our_person_id in self.current_people:
                        first_seen = self.current_people[our_person_id].get('first_seen', current_time)
                        time_in_area = current_time - first_seen
                        time_str = f"{time_in_area:.0f}s" if time_in_area < 60 else f"{time_in_area/60:.1f}m"
                    else:
                        time_str = "novo"

                    status = "Parado" if stationary else "Móvel"
                    pos_str = f"{x_pos:.1f},{y_pos:.1f}"

                    zone_desc = self.zone_manager.get_zone_description(zone)[:14]
                    print(f"{zone_desc:<15} {distance_raw:<7.2f} {pos_str:<10} {confidence:<5}% {status:<8} {time_str:<8}")

                # ✅ ENVIA DADOS COMPLETOS
                if self.gsheets_manager:
                    avg_confidence = sum(p.get("confidence", 0) for p in active_people) / len(active_people)
                    zones_detected = list(set(p.get("zone", "N/A") for p in active_people))
                    zones_str = ",".join(sorted(zones_detected))

                    if len(active_people) == 1:
                        person_description = "Pessoa Individual"
                    elif len(active_people) <= 3:
                        person_description = "Grupo Pequeno"
                    elif len(active_people) <= 10:
                        person_description = "Grupo Médio"
                    elif len(active_people) <= 20:
                        person_description = "Grupo Grande"
                    else:
                        person_description = "Multidão"

                    row = [
                        radar_id,
                        formatted_timestamp,
                        len(active_people),
                        person_description,
                        zones_str,
                        f"{sum(p.get('distance_raw', p.get('distance_smoothed', 0)) for p in active_people) / len(active_people):.1f}",
                        f"{avg_confidence:.0f}",
                        self.total_people_detected,
                        self.max_simultaneous_people
                    ]
                    self.pending_data.append(row)

                print(f"\n💡 DETECTANDO {len(active_people)} pessoa(s) SIMULTANEAMENTE")

                # ✅ ESTATÍSTICAS POR ZONA
                zone_stats = {}
                high_confidence = 0
                for person in active_people:
                    zone = person.get("zone", "N/A")
                    zone_stats[zone] = zone_stats.get(zone, 0) + 1
                    if person.get("confidence", 0) >= 70:
                        high_confidence += 1

                if zone_stats:
                    print("📊 DISTRIBUIÇÃO POR ATIVAÇÃO:")
                    for zone, count in zone_stats.items():
                        zone_desc = self.zone_manager.get_zone_description(zone)
                        print(f"   • {zone_desc}: {count} pessoa(s)")
                    print()

                print(f"✅ QUALIDADE: {high_confidence}/{len(active_people)} com alta confiança (≥70%)")

            else:
                print(f"\n👻 Nenhuma pessoa detectada no momento.")

                # Envia dados zerados apenas se houve mudança
                if self.gsheets_manager and len(self.previous_people) > 0:
                    row = [
                        radar_id, formatted_timestamp, 0, "Area_Vazia", "VAZIA",
                        "0", "0", self.total_people_detected, self.max_simultaneous_people
                    ]
                    self.pending_data.append(row)

            print("\n" + "=" * 60)
            print("🎯 SISTEMA ROBUSTO + AUTO-RECOVERY ATIVO")
            print("✅ Tracking preciso | ✅ Auto-reconexão | ✅ Anti-quota")
            print("⚡ Pressione Ctrl+C para encerrar")

            # ✅ ENVIA COM AUTO-RECOVERY
            self.send_pending_data_with_recovery()

        except Exception as e:
            logger.error(f"Erro ao processar dados JSON: {e}")
            logger.debug(f"JSON recebido: {data_json}")

    def send_pending_data_with_recovery(self):
        """Envia dados com sistema de auto-recuperação"""
        current_time = time.time()

        if (current_time - self.last_sheets_write) < self.sheets_write_interval:
            return

        if not self.pending_data or not self.gsheets_manager:
            return

        data_to_send = self.pending_data[-5:]  # Máximo 5 linhas por vez

        try:
            for row in data_to_send:
                success = self.gsheets_manager.append_row_with_auto_recovery(row)
                if success:
                    self.last_sheets_success = datetime.now()
                time.sleep(0.5)

            if data_to_send:
                logger.info(f"📊 {len(data_to_send)} linhas enviadas com auto-recovery")
                self.last_sheets_write = current_time
                self.pending_data = []

        except Exception as e:
            logger.error(f"❌ Erro no envio com recovery: {e}")

    def get_current_count(self):
        """Retorna o último person_count recebido"""
        return len(self.current_people)

    def get_total_detected(self):
        """Retorna total de pessoas detectadas na sessão"""
        return self.total_people_detected

    def get_status(self):
        """Retorna status completo do radar com estatísticas robustas"""
        return {
            'id': self.radar_id,
            'name': self.radar_name,
            'port': self.port,
            'running': self.is_running,
            'connected': self.serial_connection and self.serial_connection.is_open if self.serial_connection else False,
            'description': self.description,
            'current_count': self.get_current_count(),
            'total_detected': self.get_total_detected(),
            'max_simultaneous': self.max_simultaneous_people,
            'entries_count': self.entries_count,
            'exits_count': self.exits_count,
            'unique_people': len(self.unique_people_today),
            'people_in_area': len(self.current_people),
            'session_duration': (datetime.now() - self.session_start_time).total_seconds(),
            'system_restarts': self.system_restart_count,
            'health_status': 'healthy' if datetime.now() - self.last_data_received < timedelta(minutes=5) else 'unhealthy'
        }

def main():
    """Função principal com auto-recuperação"""
    logger.info("🚀 Iniciando Contador com Auto-Recuperação...")

    # Configura Google Sheets com auto-recovery
    script_dir = os.path.dirname(os.path.abspath(__file__))
    credentials_file = os.path.join(script_dir, 'serial_radar', 'credenciais.json')

    if not os.path.exists(credentials_file):
        logger.error(f"❌ Credenciais não encontradas: {credentials_file}")
        return

    try:
        gsheets_manager = AutoRecoveryGoogleSheetsManager(
            credentials_file,
            RADAR_CONFIG['spreadsheet_id'],
            RADAR_CONFIG['id']
        )
        logger.info("✅ Google Sheets com auto-recovery configurado")
    except Exception as e:
        logger.error(f"❌ Erro configurando Sheets: {e}")
        return

    # Inicializa radar com auto-recovery
    radar = AutoRecoveryRadarCounter(RADAR_CONFIG)

    try:
        if not radar.start(gsheets_manager):
            logger.error("❌ Falha ao iniciar radar")
            return

        # Exibe status inicial completo
        status = radar.get_status()
        logger.info("=" * 80)
        logger.info("👥 CONTADOR SANTA CRUZ v4.3 + AUTO-RECOVERY COMPLETO")
        logger.info("=" * 80)
        logger.info(f"🔴 {status['name']}: {status['port']}")
        logger.info(f"📋 {status['description']}")
        logger.info("🚀 FUNCIONALIDADES INTEGRADAS:")
        logger.info("   ✅ Sistema completo de tracking de pessoas (igual ao original)")
        logger.info("   ✅ Detecção de zonas das ativações (6 ativações específicas)")
        logger.info("   ✅ Lógica robusta de entrada/saída (anti-flickering)")
        logger.info("   ✅ Display detalhado em tempo real")
        logger.info("   ✅ Estatísticas por zona")
        logger.info("   ✅ Auto-reconexão serial inteligente")
        logger.info("   ✅ Auto-recuperação Google Sheets com retry")
        logger.info("   ✅ Monitoramento de saúde em background")
        logger.info("   ✅ Restart preventivo após 6 horas")
        logger.info("   ✅ Limpeza de memória automática")
        logger.info("   ✅ Anti-quota inteligente (30s intervalo)")
        logger.info("   ✅ Controle de token expirado")
        logger.info("🎯 RESOLUÇÃO DO PROBLEMA DE 3+ HORAS:")
        logger.info("   • Token expirado ➜ Renovação automática")
        logger.info("   • Quota exceeded ➜ Backoff inteligente")
        logger.info("   • Conexão serial perdida ➜ Reconexão automática")
        logger.info("   • Memória alta ➜ Limpeza automática")
        logger.info("   • Sistema travado ➜ Restart preventivo")
        logger.info("⚡ Sistema HÍBRIDO: Funcionalidades completas + Auto-recovery")
        logger.info("🔄 Reconexão automática habilitada para todos os componentes")
        logger.info("=" * 80)

        # Loop principal melhorado
        status_counter = 0
        while True:
            time.sleep(5)  # Verifica a cada 5 segundos
            status_counter += 1

            # Status detalhado a cada 30 segundos (6 * 5s = 30s)
            if status_counter >= 6:
                status_counter = 0
                status = radar.get_status()
                current_count = status['people_in_area']
                total_detected = status['total_detected']
                max_simultaneous = status['max_simultaneous']
                entries = status['entries_count']
                exits = status['exits_count']
                unique_people = status['unique_people']
                restarts = status['system_restarts']
                health = status['health_status']

                # Status baseado na saúde do sistema
                if health == 'healthy' and radar.is_running and radar.serial_connection and radar.serial_connection.is_open:
                    logger.info(f"💚 SAUDÁVEL: {current_count} ativas | {total_detected} total | {entries} entradas | {exits} saídas | {unique_people} únicas | Máx: {max_simultaneous} | Restarts: {restarts}")
                elif radar.is_running:
                    logger.warning(f"💛 PROBLEMAS: Radar rodando mas conexão instável - tentando auto-recovery...")
                else:
                    logger.error(f"❌ CRÍTICO: Radar não está ativo - sistema parado")

                # Verifica saúde do Google Sheets
                if gsheets_manager.health_check():
                    logger.info(f"📊 PLANILHA: Funcionando normalmente")
                else:
                    logger.warning(f"📊 PLANILHA: Problemas detectados - executando auto-recovery...")

    except KeyboardInterrupt:
        logger.info("🛑 Encerrando por solicitação do usuário...")

    except Exception as e:
        logger.error(f"❌ Erro inesperado: {str(e)}")
        logger.error(traceback.format_exc())

    finally:
        radar.stop()
        logger.info("✅ Sistema encerrado!")

if __name__ == "__main__":
    main()