# -*- coding: utf-8 -*-
"""teste_conexao

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mpa_5WpBimjR0vIYNerW9GqQgOilkQma
"""

#!/usr/bin/env python3
import serial
import serial.tools.list_ports
import time

def test_serial_connections():
    print("🔍 TESTE DE CONEXÕES SERIAIS")
    print("=" * 50)

    # Detectar portas
    ports = list(serial.tools.list_ports.comports())
    print(f"📡 PORTAS DETECTADAS: {len(ports)}")
    for i, port in enumerate(ports):
        print(f"  {i+1}. {port.device} - {port.description}")
    print()

    # Testar conexões específicas
    test_ports = ['/dev/ttyACM0', '/dev/ttyACM1']

    for port_name in test_ports:
        print(f"🔌 TESTANDO {port_name}...")
        try:
            ser = serial.Serial(
                port=port_name,
                baudrate=115200,
                timeout=2
            )
            print(f"✅ {port_name}: CONECTADO")

            # Tentar ler alguns dados
            print(f"📖 Lendo dados por 3 segundos...")
            start_time = time.time()
            data_count = 0

            while time.time() - start_time < 3:
                if ser.in_waiting > 0:
                    data = ser.read(ser.in_waiting)
                    if data:
                        data_count += len(data)
                time.sleep(0.1)

            print(f"📊 Bytes recebidos: {data_count}")
            if data_count > 0:
                print(f"✅ {port_name}: DADOS DETECTADOS")
            else:
                print(f"⚠️ {port_name}: SEM DADOS")

            ser.close()
            print()

        except Exception as e:
            print(f"❌ {port_name}: ERRO - {e}")
            print()

if __name__ == "__main__":
    test_serial_connections()